services:
    stagia_user.registration.form.type:
        class: Stagia\UtilisateurBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: stagia_user_registration }
    stagia_user.profile.form.type:
        class: Stagia\UtilisateurBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: stagia_user_profile }