imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        less: ~
        lessphp:
            apply_to: "\.less$"
            file:   %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            formatter: "compressed"
            preserve_comments: false
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  gmail
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:  stagia91@gmail.com
    password:  Stagia91000
    spool:     { type: memory }
    
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: Stagia\UtilisateurBundle\Entity\Utilisateur
    registration:
        form:
            type: stagia_user_registration
        confirmation:
            enabled:    true
            from_email:
                address:        registration@stagia.com
                sender_name:    Stagia
    from_email:
        address:        noreply@stagia.com
        sender_name:    Stagia
    resetting:
        email:
            from_email:
                address:        resetting@stagia.com
                sender_name:    Stagia
    profile:
        form:
            type: fos_user_profile_edit

mopa_bootstrap:
    form: 
      show_legend: false
      render_optional_text: false
    menu: ~
    icons:
        icon_set: fontawesome4
        shortcut: icon
    initializr:
        meta:
            title:        "Stagia"
            description:  "Trouver votre stage ou votre stagiaire et suivez les mémoires d'autres étudiants"
            keywords:     "stage,stages,memoires,etudiant,fac,evry"
            author_name:  "UEVE"
            author_url:   "/human.txt"
            nofollow:     false
            noindex:      false 
        dns_prefetch:
              - '//ajax.googleapis.com'
        google:
            wt: 'xxx'
            analytics: 'UA-xxxxxxx-xx'
        diagnostic_mode: false
        