security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MAITRE_APPRENTISSAGE: ROLE_USER
        ROLE_RESPONSABLE: ROLE_USER
        ROLE_TUTEUR: ROLE_USER
        ROLE_ETUDIANT: ROLE_USER
        ROLE_RESPONSABLE_FORMATION: ROLE_USER
        ROLE_ADMIN:       [ROLE_RESPONSABLE, ROLE_TUTEUR, ROLE_ETUDIANT, ROLE_RESPONSABLE_FORMATION, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }