Stagia\AppBundle\Entity\Fichier:
    type: entity
    table: fichier
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        chemin:
            type: string
            length: 255