Stagia\AppBundle\Entity\Stage:
    type: entity
    table: stages
    indexes:
        name_index:
          columns: [ titre ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 100
            nullable: false
            options:
                default: ""
        description:
            type: text
        date_debut:
            type: date
        date_fin:
            type: date
        competences:
            type: text
        date_publication:
            type: date
        lieu:
            type: string
            length: 200
            nullable: true
        remuneration:
            type: integer
            nullable: true
            options:
                default: 0
        conventionDeStage:
            type: boolean
            nullable: false
            options:
                comment: Détermine si l'étudiant doit disposer d'une offre de stage
        active:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        utilisateur_createur:
            targetEntity: Stagia\UtilisateurBundle\Entity\Utilisateur
            inversedBy: stage
            joinColumn:
              name: utilisateur_createur_id
              referencedColumnName: id
              nullable: false

                
