Stagia\AppBundle\Entity\Sujet:
    type: entity
    table: sujet
    indexes:
        name_index:
            columns: [ nom ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 100
            nullable: false
            options:
                default: ""
        description:
            type: text
        date_creation:
            type: date
        validation:
            type: boolean
            nullable: false
            options:
                default: false
                
    oneToMany:
        commentaires:
            targetEntity: Commentaire
            orphanRemoval: true
            mappedBy: sujet
            orderBy:
                date_creation: ASC
            cascade: [ persist ]
            
    manyToOne:
        utilisateur_createur:
            targetEntity: \Stagia\UtilisateurBundle\Entity\Utilisateur
            inversedBy: sujet
        
        
        