Stagia\UtilisateurBundle\Entity\Utilisateur:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: true
            options:
                default: null
        prenom:
            type: string
            nullable: true
            options:
                default: null
        rue:
            type: string
            nullable: true
            options:
                default: null
        adresse1:
            type: string
            nullable: true
            options:
                default: null
        adresse2:
            type: string
            nullable: true
            options:
                default: null
        codepostal:
            type: string
            nullable: true
            options: 
                default: null
        ville:
            type: string
            nullable: true
            options:
                default: null
        telephone:
            type: string(20)
            nullable: true
            options:
                default: null
        
            