commentaire:
    path:     /
    defaults: { _controller: "StagiaAppBundle:Commentaire:index" }

commentaire_show:
    path:     /{id}/Afficher
    defaults: { _controller: "StagiaAppBundle:Commentaire:show" }

commentaire_create:
    path:     /Creer
    defaults: { _controller: "StagiaAppBundle:Commentaire:create" }
    methods:  POST

commentaire_edit:
    path:     /{id}/Modifier
    defaults: { _controller: "StagiaAppBundle:Commentaire:edit" }

commentaire_update:
    path:     /{id}/MisAJour
    defaults: { _controller: "StagiaAppBundle:Commentaire:update" }
    methods:  [POST, PUT]

commentaire_delete:
    path:     /{id}/Supprimer
    defaults: { _controller: "StagiaAppBundle:Commentaire:delete" }
    methods:  [POST, DELETE]

commentaire_post:
    path:   /NouveauCommentaire/{sujet_id}
    defaults: { _controller: "StagiaAppBundle:Commentaire:post" }
    methods:  [POST, PUT]