commentaire_edit:
    path:     /{id}/Modifier
    defaults: { _controller: "StagiaAppBundle:Commentaire:edit" }

commentaire_update:
    path:     /{id}/MisAJour
    defaults: { _controller: "StagiaAppBundle:Commentaire:update" }
    methods:  [POST, PUT]

commentaire_delete:
    path:     /{id}/Supprimer
    defaults: { _controller: "StagiaAppBundle:Commentaire:delete" }

commentaire_post:
    path:   /NouveauCommentaire/{sujet_id}
    defaults: { _controller: "StagiaAppBundle:Commentaire:post" }
    methods:  [POST, PUT]