commentaire:
    path:     /
    defaults: { _controller: "StagiaAppBundle:Commentaire:index" }

commentaire_show:
    path:     /{id}/show
    defaults: { _controller: "StagiaAppBundle:Commentaire:show" }

commentaire_new:
    path:     /new
    defaults: { _controller: "StagiaAppBundle:Commentaire:new" }

commentaire_create:
    path:     /create
    defaults: { _controller: "StagiaAppBundle:Commentaire:create" }
    methods:  POST

commentaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "StagiaAppBundle:Commentaire:edit" }

commentaire_update:
    path:     /{id}/update
    defaults: { _controller: "StagiaAppBundle:Commentaire:update" }
    methods:  [POST, PUT]

commentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "StagiaAppBundle:Commentaire:delete" }
    methods:  [POST, DELETE]
