competence:
    path:     /
    defaults: { _controller: "StagiaAppBundle:Competence:index" }

competence_show:
    path:     /{id}/Afficher
    defaults: { _controller: "StagiaAppBundle:Competence:show" }

competence_new:
    path:     /Nouveau
    defaults: { _controller: "StagiaAppBundle:Competence:new" }

competence_create:
    path:     /Creer
    defaults: { _controller: "StagiaAppBundle:Competence:create" }
    methods:  POST

competence_edit:
    path:     /{id}/Modifier
    defaults: { _controller: "StagiaAppBundle:Competence:edit" }

competence_update:
    path:     /{id}/MisAJour
    defaults: { _controller: "StagiaAppBundle:Competence:update" }
    methods:  [POST, PUT]

competence_delete:
    path:     /{id}/Supprimer
    defaults: { _controller: "StagiaAppBundle:Competence:delete" }
    methods:  [POST, DELETE]
