memoire:
    path:     /
    defaults: { _controller: "StagiaAppBundle:Memoire:index" }

memoire_show:
    path:     /{id}/show
    defaults: { _controller: "StagiaAppBundle:Memoire:show" }

memoire_new:
    path:     /new
    defaults: { _controller: "StagiaAppBundle:Memoire:new" }

memoire_create:
    path:     /create
    defaults: { _controller: "StagiaAppBundle:Memoire:create" }
    methods:  POST

memoire_edit:
    path:     /{id}/edit
    defaults: { _controller: "StagiaAppBundle:Memoire:edit" }

memoire_update:
    path:     /{id}/update
    defaults: { _controller: "StagiaAppBundle:Memoire:update" }
    methods:  [POST, PUT]

memoire_delete:
    path:     /{id}/delete
    defaults: { _controller: "StagiaAppBundle:Memoire:delete" }
    methods:  [POST, DELETE]
