stage:
    path:     /
    defaults: { _controller: "StagiaAppBundle:Stage:index" }

stage_show:
    path:     /{id}/Afficher
    defaults: { _controller: "StagiaAppBundle:Stage:show" }

stage_new:
    path:     /Nouveau
    defaults: { _controller: "StagiaAppBundle:Stage:new" }

stage_create:
    path:     /Creer
    defaults: { _controller: "StagiaAppBundle:Stage:create" }
    methods:  POST

stage_edit:
    path:     /{id}/Modifier
    defaults: { _controller: "StagiaAppBundle:Stage:edit" }

stage_update:
    path:     /{id}/MisAJour
    defaults: { _controller: "StagiaAppBundle:Stage:update" }
    methods:  [POST, PUT]

stage_delete:
    path:     /{id}/Supprimer
    defaults: { _controller: "StagiaAppBundle:Stage:delete" }
